### PR TITLE
Add assets

### PR DESCRIPTION
**Pull request by jkwok91**
And a step for user to incorporate assets into their project.
Also, fix formatting for markcop.

Words needed in markcop dictionary:
- FGL

### CODE REVIEW

**Comment by ad510** [comment]
Yay, thanks!

I think it should be ok to hotlink to the images with URLs like https://raw.githubusercontent.com/jkwok91/hackclub/bigfoot/workshops/find_bigfoot/assets/bigfoot.png (change jkwok91 to hackclub). This would be simpler than needing the steps to copy the images over. For example the personal website workshop hotlinks to imgur.

**Comment by ad510** [comment]
Also the image URLs in the example folder need to be updated.

**Comment by jkwok91** [comment]
I also considered hotlinking, but @zachlatta said it'd be troublesome to edit later on.
@zachlatta, thoughts?

I've fixed the examples!

**Comment by zachlatta** [comment]
Worries about hotlinking:
- Unless we link to the specific commit (ex.
  https://raw.githubusercontent.com/hackclub/hackclub/ce5bf57d947a5e17ba56df848c7bb1a8a60ab5b0/workshops/maze/img/demo.gif),
  if the images are ever renamed, it'll break the hackers' websites
- If we do link to the image in a specific commit, it's a huge pain to
  update images later
  - If I want to edit an image, I need to find all places it's hotlinked to
    and update them to the latest image's commit (huge pain, especially since
    updating the links has to happen in a separate commit)

On Thu, Feb 11, 2016 at 8:40 AM, JESSICA notifications@github.com wrote:

> I also considered hotlinking, but @zachlatta
> https://github.com/zachlatta said it'd be troublesome to edit later on.
> @zachlatta https://github.com/zachlatta, thoughts?
> 
> I've fixed the examples!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ad510/hackclub/pull/1#issuecomment-182948635.

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by ad510** [comment]
@zachlatta It's not _that_ hard to update all the hotlink URLs, right? See [here](https://stackoverflow.com/questions/15402770/how-to-grep-and-replace) for example.

Anyway, I don't think updating the images is something we'd have to do often, and even if it is, I think it's more important to make things easy for hackers doing the workshop than it is to make things easy for maintainers. I'd personally be fine with putting the images on imgur then hotlinking to them.

**Comment by ad510** [comment]
Actually, let me pull your changes and try the renaming myself, so I can see how easy or hard it is.

**Comment by ad510** [comment]
How do you wrap to 80 chars, btw?

**Comment by zachlatta** [comment]
In vim it's `gq` once you've selected the text using visual mode.

Will get back to your hotlinks comment after my next series of calls :-).

On Thu, Feb 11, 2016 at 4:20 PM, Andrew Downing notifications@github.com
wrote:

> How do you wrap to 80 chars, btw?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ad510/hackclub/pull/1#issuecomment-183122049.

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by ad510** [comment]
The renaming was easy, but there's some other polish I'm doing that's taking longer. Going to class now, will update you afterward.

**Comment by zachlatta** [comment]
> @zachlatta It's not that hard to update all the hotlink URLs, right? See here
> for example.

That's so much harder than if they're relative links though! Other bonus of
having them download then upload images from a directory on our GitHub: now they
know how to add their own images, from scratch (though I guess this would apply
to knowing how to right click and click `Copy Image Address` on any site on the
internet though).

On Thu, Feb 11, 2016 at 5:03 PM, Andrew Downing notifications@github.com
wrote:

> The renaming was easy, but there's some other polish I'm doing that's
> taking longer. Going to class now, will update you afterward.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ad510/hackclub/pull/1#issuecomment-183136894.

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by ad510** [comment]
@zachlatta Sorry for the delay in the Bigfoot workshop, I wasn't feeling well last night or this morning.

Can we rely on the school computers being able to save images locally, and being able to use the same directions to save the images across different web browsers? Also @jkwok91's directions to get the images is missing some steps; for each image you have to click the file link, then right click the image to save, then go back to the folder.

I'm thinking we could put the images either on gh-pages of a separate repo (hackclub.github.io/workshop-assets/bigfoot/trees.jpg), or directly on the hack club website (assets.hackclub.com/bigfoot/trees.jpg), so we don't have to worry about renames. Updating a URL takes less than a minute (I tried it). I'm about to update my pull request to work this way.

If people really want to have a local copy of the images, I'm sure they can Google how to do it. :smile:

**Comment by zachlatta** [comment]
> Can we rely on the school computers being able to save images locally, and
> being able to save the images across different web browsers?
> 
> I think that's an assumption we'll have to make for the time being.
> 
> Also @jkwok91's directions to get the images is missing some steps; for
> each image you have to click the file link, then right click the image to
> save, then go back to the folder.
> 
> Good catch! Can you add what's missing to the workshop?
> 
> I'm thinking we could put the images either on gh-pages of a separate repo
> (hackclub.github.io/workshop-assets/bigfoot/trees.jpg), or directly on
> the hack club website (assets.hackclub.com/bigfoot/trees.jpg), so we
> don't have to worry about renames. Updating a URL takes less than a minute
> (I tried it). I'm about to update my pull request to work this way.
> 
> I replied in hackclub/hackclub#669 about this. Basically I don't think it's
> a good idea for a two reasons:
1. Markcop can't automatically check the validity of links if they're in
   a separate repo/webiste
2. This'll raise the contribution barrier for new contributors (now if
   they want to make an asset change, they have to submit two pull requests in
   two separate repos)

On Fri, Feb 12, 2016 at 4:53 PM, Andrew Downing notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta Sorry for the delay in the
> Bigfoot workshop, I wasn't feeling well last night or this morning.
> 
> Can we rely on the school computers being able to save images locally, and
> being able to save the images across different web browsers? Also @jkwok91
> https://github.com/jkwok91's directions to get the images is missing
> some steps; for each image you have to click the file link, then right
> click the image to save, then go back to the folder.
> 
> I'm thinking we could put the images either on gh-pages of a separate repo
> (hackclub.github.io/workshop-assets/bigfoot/trees.jpg), or directly on
> the hack club website (assets.hackclub.com/bigfoot/trees.jpg), so we
> don't have to worry about renames. Updating a URL takes less than a minute
> (I tried it). I'm about to update my pull request to work this way.
> 
> If people really want to have a local copy of the images, I'm sure they
> can Google how to do it. [image: :smile:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ad510/hackclub/pull/1#issuecomment-183548256.

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by ad510** [comment]
One more thing I missed: the link to https://github.com/jonleung/hackclub/tree/add-personal-website-workshop/workshops/personal_website#user-content-6-adding-an-image-with-the-image-tag should be changed to https://github.com/hackclub/hackclub/tree/master/workshops/personal_website#user-content-6-adding-an-image-with-the-image-tag (it was still on jonleung's branch) when I originally wrote the workshop).

@jkwok91 After fixing that, can you go ahead and merge this directly into hackclub/hackclub? There are some minor improvements I wanted to make, but I won't have much time for it this week and I can do that after this is merged.

**Comment by zachlatta** [comment]
Before @jkwok91 merges, can you update this to have relative links @ad510? Reasoning included in my above comments.

**Comment by jkwok91** [comment]
Hey @ad510, I'm going to change it back to having relative links, for the sake of getting this merged ASAP. I'll add the tips you mentioned about "clicking on each image link" and "file > save as" and "clicking back after each image," as well as the URL change. :grin:

**Comment by ad510** [comment]
This PR already uses relative links. What I meant was to merge this PR directly into hackclub/hackclub, instead of trying to merge it into ad510/hackclub and dealing with the merge conflicts.

**Pull request closed without merging**
